### ISSUE TITLE
if in guis like adding minecraft server it crashes when trying to type something in 

### ISSUE THREAD

**Issue by elpolake** [Spilios06/Vanguard#1]
add an if statement in onkeypress event that checks if current instance is instance of screen public void onKeyPress(int key, int action) {
		if (!(MinecraftClient.getInstance().currentScreen instanceof Screen)) { // Avoid module toggles in any GUI screen
			if (action == GLFW.GLFW_PRESS) {
				for (Module module : ModuleManager.INSTANCE.modules) {
					if (key == module.key) {
						module.toggle();
					}
				}
			}
		}
	}

**Comment by Spilios06** [comment]
Added a check to ensure the player is not null before the keyPress event.
