### ISSUE TITLE
numbersetting not working

### ISSUE THREAD

**Issue by elpolake** [Spilios06/Vanguard#2]
instead of using number setting use slidersetting

**Comment by Spilios06** [comment]
Have not implemented the number settings into the GUI yet, I am trying to decide whether I should make it with a slider or by typing in a value since I am anyway going to have to implement that logic in for the keybind setting so I can be done with the GUI (for now at least)

**Comment by Spilios06** [comment]
> instead of using number setting use slidersetting

I see you made a fork trying to implement a slider, you can make a pull request if you want so I can add your changes.

**Comment by Spilios06** [comment]
Fixed number setting
